### ISSUE TITLE
Update org.kde.Platform runtime to 5.15-23.08

### ISSUE THREAD

**Issue by rmbleeker** [flathub/com.ozmartians.VidCutter#32]
I realize I filed report #29 only a month ago, but since then org.kde.Platform branch 5.15-23.08 has been released. Perhaps the VidCutter flatpak can be updated again to make use of the latest runtime so it's more future-proof?

**Comment by ozmartian** [comment]
This will be done soon. Thanks for the reminder though! Much appreciated.






---- On Wed, 08 Nov 2023 23:52:46 +1100 Ruud Bleeker ***@***.***> wrote ---





I realize I filed report https://github.com/flathub/com.ozmartians.VidCutter/issues/29 only a month ago, but since then org.kde.Platform branch 5.15-23.08 has been released. Perhaps the VidCutter flatpak can be updated again to make use of the latest runtime so it's more future-proof?
